const EXECUTION_STRATEGIES = Object.freeze({
  CACHE: 'CACHE',
  DETERMINISTIC_RULES: 'DETERMINISTIC_RULES',
  SQL_ANALYTICS: 'SQL_ANALYTICS',
  STATISTICAL_MODEL: 'STATISTICAL_MODEL',
  GEOSPATIAL_ENGINE: 'GEOSPATIAL_ENGINE',
  OPTIMIZATION_ENGINE: 'OPTIMIZATION_ENGINE',
  CONVENTIONAL_ML: 'CONVENTIONAL_ML',
  LOCAL_MODEL: 'LOCAL_MODEL',
  HOSTED_ECONOMY_MODEL: 'HOSTED_ECONOMY_MODEL',
  HOSTED_BALANCED_MODEL: 'HOSTED_BALANCED_MODEL',
  HOSTED_PREMIUM_MODEL: 'HOSTED_PREMIUM_MODEL',
  MULTI_MODEL_WORKFLOW: 'MULTI_MODEL_WORKFLOW',
  HUMAN_REVIEW: 'HUMAN_REVIEW'
});

const EXECUTION_PROFILES = Object.freeze({
  DETERMINISTIC_ONLY: 'DETERMINISTIC_ONLY',
  ULTRA_LOW_COST: 'ULTRA_LOW_COST',
  BALANCED: 'BALANCED',
  REAL_TIME_OPERATIONAL: 'REAL_TIME_OPERATIONAL',
  BACKGROUND_BATCH: 'BACKGROUND_BATCH',
  SAFETY_CRITICAL: 'SAFETY_CRITICAL',
  PRIVACY_RESTRICTED: 'PRIVACY_RESTRICTED',
  PREMIUM_APPROVAL_REQUIRED: 'PREMIUM_APPROVAL_REQUIRED'
});

const MODEL_CLASSES = Object.freeze({
  LOCAL_LIGHTWEIGHT: 'LOCAL_LIGHTWEIGHT',
  HOSTED_ECONOMY: 'HOSTED_ECONOMY',
  HOSTED_BALANCED: 'HOSTED_BALANCED',
  HOSTED_PREMIUM: 'HOSTED_PREMIUM',
  EMBEDDING: 'EMBEDDING',
  SPEECH_TO_TEXT: 'SPEECH_TO_TEXT',
  TEXT_TO_SPEECH: 'TEXT_TO_SPEECH',
  VISION: 'VISION',
  MULTIMODAL: 'MULTIMODAL'
});

const REQUEST_SCHEMA_VERSION = 'intelligence.request.v1';
const RESPONSE_SCHEMA_VERSION = 'intelligence.response.v1';
const POLICY_VERSION = 'intelligence.policy.default.v1';

module.exports = {
  EXECUTION_PROFILES,
  EXECUTION_STRATEGIES,
  MODEL_CLASSES,
  POLICY_VERSION,
  REQUEST_SCHEMA_VERSION,
  RESPONSE_SCHEMA_VERSION
};
